import { IsString, IsNotEmpty } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class FcmTokenDto {
  @ApiProperty({ description: 'The device FCM Token generated by Firebase SDK' })
  @IsString()
  @IsNotEmpty()
  token: string;
}
